repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: airflow
    namespace: default
    chart: bitnami/airflow
    version: 16.8.3

  - name: apache
    namespace: default
    chart: bitnami/apache
    version: 11.2.14

  - name: apisix
    namespace: default
    chart: bitnami/apisix
    version: 2.10.0

  # ... 他のチャートの設定 ...

  - name: wordpress
    namespace: default
    chart: bitnami/wordpress
    version: 18.1.30

  - name: zookeeper
    namespace: default
    chart: bitnami/zookeeper
    version: 12.12.1

  # 以下、他のチャートの設定を追加
  - name: appsmith
    namespace: default
    chart: bitnami/appsmith
    version: 2.8.5

  - name: argo-cd
    namespace: default
    chart: bitnami/argo-cd
    version: 5.10.6

  - name: argo-workflows
    namespace: default
    chart: bitnami/argo-workflows
    version: 6.8.1

  - name: aspnet-core
    namespace: default
    chart: bitnami/aspnet-core
    version: 4.4.10

  - name: cassandra
    namespace: default
    chart: bitnami/cassandra
    version: 10.12.1
