---
name: actionlint
on:
  push:
    branches: [main]
    paths:
      - .github/**
  pull_request:
    branches: [main]
    paths:
      - .github/**
permissions: {}
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquaproj/aqua-installer@v2
        with:
          aqua_version: v2.21.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: |
          golangci-lint version
          golangci-lint run

