---
name: actionlint
on:
  push:
    branches: [main]
    paths:
      - .github/**
  pull_request:
    branches: [main]
    paths:
      - .github/**
permissions: {}
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquaproj/aqua-installer@fd2089d1f56724d6456f24d58605e6964deae124 # v2.3.2
        with:
          aqua_version: v2.37.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: |
          actionlint -ignore 'Useless cat'
        name: actionlint
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: |
          golangci-lint version
          golangci-lint run || :
        name: golangci-lint

