---
name: test-update
on:
  pull_request:
    branches: [test]
permissions: {}
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: actions/dependency-review-action@v3
      - uses: actions/deploy-pages@v4
      - uses: actions/first-interaction@v1.0.0
      - uses: actions/github-script@0.3.0
      - uses: actions/setup-node@v4
      - uses: actions/stale@v8
      - uses: actions/typescript-action@v1
      - uses: actions/upload-pages-artifact@v3      
