---
name: test-update
on:
  pull_request:
    branches: [test]
permissions: {}
jobs:
  default1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: prime-numbers
          key: ${{ runner.os }}-primes
      - uses: actions/checkout@v4.1.1
      - uses: actions/configure-pages@v3.0.7
      - uses: actions/delete-package-versions@v4.0.0
      - uses: actions/dependency-review-action@v3
      - uses: actions/deploy-pages@v4
      - uses: actions/download-artifact@v4.1.0
      - uses: actions/first-interaction@v1.3.0
      - uses: actions/github-script@v7.0.1
      - uses: actions/go-dependency-submission@1.0.1
      - uses: actions/javascript-action@1.0.1
      - uses: actions/labeler@v5.0.0
      - uses: actions/setup-dotnet@3.1.0
      - uses: actions/setup-go@v4.0.0
      - uses: actions/setup-java@v4.0.0
      - uses: actions/setup-node@v4
      - uses: actions/setup-python@v5.0
      - uses: actions/setup-ruby@1.3.0
      - uses: actions/stale@v8
      - uses: actions/typescript-action@v1
      - uses: actions/upload-artifact@v4.0.0
      - uses: actions/upload-pages-artifact@v3
  default2:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/scp-action@v0.1.7
      - uses: armbian/build@v23.11.2
      - uses: di-sukharev/opencommit@github-action-v1.0.2
      - uses: JamesIves/github-pages-deploy-action@v4.5.0
      - uses: lowlighter/metrics@v3.34
      - uses: mikefarah/yq@v4.40.5
      - uses: peaceiris/actions-gh-pages@v3.9.3
      - uses: securego/gosec@v2.18.2
      - uses: super-linter/super-linter@v5.7.2
      - uses: trufflesecurity/trufflehog@v3.63.7
