---
name: test-update
on:
  pull_request:
    branches: [test]
permissions: {}
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: prime-numbers
          key: ${{ runner.os }}-primes
      - uses: actions/checkout@v4.1.1
      - uses: actions/dependency-review-action@v3
      - uses: actions/deploy-pages@v4
      - uses: actions/download-artifact@v4.1.0
      - uses: actions/first-interaction@v1.3.0
      - uses: actions/github-script@0.3.0
      - uses: actions/labeler@v5.0.0
      - uses: actions/setup-dotnet@3.1.0
      - uses: actions/setup-go@v4.1.0
      - uses: actions/setup-java@v4.0.0
      - uses: actions/setup-node@v4
      - uses: actions/setup-python@v5.0
      - uses: actions/setup-ruby@1.3.0
      - uses: actions/stale@v8
      - uses: actions/typescript-action@v1
      - uses: actions/upload-artifact@v4.0.0
      - uses: actions/upload-pages-artifact@v3
